// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/profile': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/profile.get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/profile.put').default>>>>
    }
    '/api/auth/refresh': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/refresh.post').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>>
    }
    '/api/collection-animes': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/collection-animes.get').default>>>>
    }
    '/api/collection-mangas': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/collection-mangas.get').default>>>>
    }
    '/api/collections/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/collections/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/collections/[id].get').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/collections/[id].patch').default>>>>
    }
    '/api/collections/:id/animes': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/collections/[id]/animes.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/collections/[id]/animes.post').default>>>>
    }
    '/api/collections/:id/animes/:animeId': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/collections/[id]/animes/[animeId].delete').default>>>>
    }
    '/api/collections/:id/mangas': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/collections/[id]/mangas.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/collections/[id]/mangas.post').default>>>>
    }
    '/api/collections/:id/mangas/:mangaId': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/collections/[id]/mangas/[mangaId].delete').default>>>>
    }
    '/api/collections': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/collections/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/collections/index.post').default>>>>
    }
    '/api/collections/my': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/collections/my.get').default>>>>
    }
    '/api/proxy/animes': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/proxy/animes.get').default>>>>
    }
    '/api/proxy/articles': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/proxy/articles.get').default>>>>
    }
    '/api/proxy/articles/featured': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/proxy/articles/featured.get').default>>>>
    }
    '/api/proxy/articles/slug/:slug': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/proxy/articles/slug/[slug].get').default>>>>
    }
    '/api/proxy/categories': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/proxy/categories.get').default>>>>
    }
    '/api/proxy/mangas': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/proxy/mangas.get').default>>>>
    }
    '/api/proxy/reviews': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/proxy/reviews.get').default>>>>
    }
    '/api/reviews/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reviews/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reviews/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reviews/[id].put').default>>>>
    }
    '/api/reviews': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reviews/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reviews/index.post').default>>>>
    }
    '/api/reviews/my': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reviews/my.get').default>>>>
    }
    '/api/reviews/stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reviews/stats.get').default>>>>
    }
    '/api/reviews/top': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reviews/top.get').default>>>>
    }
    '/api/reviews/user/:userId': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reviews/user/[userId].get').default>>>>
    }
    '/api/seasons/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/seasons/[id].get').default>>>>
    }
    '/api/seasons/:id/animes': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/seasons/[id]/animes.get').default>>>>
    }
    '/api/seasons/current': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/seasons/current.get').default>>>>
    }
    '/api/seasons': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/seasons/index.get').default>>>>
    }
    '/api/webzine/img/**:path': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/webzine/img/[...path].get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}