// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/28/2025, 9:24:00 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/zohardus/www/ak9project/frontendv2/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/zohardus/www/ak9project/frontendv2/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/zohardus/www/ak9project/frontendv2/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/zohardus/www/ak9project/frontendv2/components/articles/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/zohardus/www/ak9project/frontendv2/components/reviews/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/zohardus/www/ak9project/frontendv2/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/zohardus/www/ak9project/frontendv2/plugins/**/*.{js,ts,mjs}","/home/zohardus/www/ak9project/frontendv2/composables/**/*.{js,ts,mjs}","/home/zohardus/www/ak9project/frontendv2/utils/**/*.{js,ts,mjs}","/home/zohardus/www/ak9project/frontendv2/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/zohardus/www/ak9project/frontendv2/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/zohardus/www/ak9project/frontendv2/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/zohardus/www/ak9project/frontendv2/app.config.{js,ts,mjs}","/home/zohardus/www/ak9project/frontendv2/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;